name: 'Auto Release Draft'
description: 'Drafts a GitHub rlease with the changes introduced by a newly created version tag.'
author: 'Chris Bo'
outputs:
  release-url: 'The URL of the GitHub release that was drafted'
runs:
  using: 'node12'
  main: 'dist/index.js'
